config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true

  mount_uploader :picture, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :ingredient_id, :uniqueness => { :scope => :cocktail_id }
  validates :cocktail_id, :uniqueness => { :scope => :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :info, :picture)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktails, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.new(dose_params)
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_back(fallback_location: cocktail_path)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktails
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-sm-4">
          <%= link_to cocktail_path(cocktail) do %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.picture, height: 300, width: 400, crop: :fill %>');">
              <div class="card-category"><h2><%= cocktail.name %></h2></div>
              <div class="card-description">
                <p><%= cocktail.info %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Add your cocktail</h1>
<hr>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :info %>
  <%= f.input :picture %>
  <%= f.input :picture_cache, as: :hidden %>
  <%= f.submit "Add a cocktail", class: "btn btn-treehouse" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path @cocktail.picture, height: 300, width: 400, crop: :fill %>');">
  <div class="banner-content">
    <h2><%= @cocktail.name %></h2>
    <p><%= @cocktail.info %></p>
  </div>
</div>
<br>
<% @cocktail.doses.each do |dose| %>
  <p><%= dose.description %> of <%= dose.ingredient.name %></p>
  <%= link_to "Delete", dose_path(dose), data: {:confirm => 'Are you sure?'}, method: :delete %>
<% end %>

<%= link_to "Add dose", new_cocktail_dose_path(@cocktail) %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Add a dose", class: "btn btn-treehouse" %>
<% end %>

app/views/layouts/_footer.html.erb
<hr>

<div class="footer">
  <div class="footer-copyright">
    <p>This website is made with Ruby on Rails by Maxime</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="center">
    <%= link_to root_path do %>
      <%= image_tag "glass.png" %>
    <% end %>
  </div>

  <%= link_to root_path do %>
    <h1>Mister Cocktail</h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="center navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Add your cocktail", new_cocktail_path, class: "btn-treehouse" %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Add your cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>